/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.moznion.aws.xray.play2;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
